Homework12
coctel99/homework-repository pull request #12
Opened 2021-12-30 23:51 UTC by coctel99

2022-01-10 06:32 UTC, matacoder requested changes
Нужно немного упростить модели.

2022-01-10 06:32 UTC, matacoder commented on homework12/classes.py
> +class Student(User):
Мне не до конца понятно, зачем ты наследуешься от юзера здесь.
Если тебе нужно знать статус юзера, ты можешь сделать либо булево поле is_student, is_teacher в модели User, либо отдельную таблицу Teacher с полем перечислением id юзеров, но там точно не нужно дублировать имя и фамилию.
Упрости, пожалуйста, решение, не нужно лишних колонок в БД.

2022-01-10 06:32 UTC, matacoder commented on tests/homework12/test_task1.py
> +    assert (homework_rows_num > 0 and homework_result__rows_num > 0
0 - это false. А значит можно использовать assert all(argrs) здесь для простоты

2022-01-10 06:32 UTC, matacoder commented on homework12/classes.py
> +    def __init__(self, first_name: str, last_name: str):
Почему здесь есть инит, а в других местах нет? Поля ведь по другому называются. Нужен ли инит в ORM?

2022-01-10 08:09 UTC, coctel99 commented on homework12/classes.py
> +    def __init__(self, first_name: str, last_name: str):
Инита нет только у классов Student и Teacher, чтобы использовать инит родительского класса User. ORM напрямую с инитом не работает, но он нужен, чтобы создать инстансы классов, с которыми потом ORM и будет работать. В create_records.py я инициализирую инстансы классов Student и Teacher, а затем, вызывая их методы, создаю инстансы классов Homework и HomeworkResult. Всего получается по 1 инстансу каждого класса, которые добавляются в сессию ORM с помощью session.add() и записываются в бд с помощью session.commit()

2022-01-12 07:36 UTC, matacoder requested changes
Упрощаем модели
https://pastebin.com/Upg9gMVv

2022-01-12 07:36 UTC, matacoder commented on homework12/classes.py
> +class Teacher(User):
https://pastebin.com/Upg9gMVv
Посмотри как можно сделать учителя/студента

2022-01-19 07:38 UTC, matacoder requested changes
Чуть доработать модели

2022-01-19 07:38 UTC, matacoder commented on homework12/models.py
> +class Student(User):
Наследуешься от Юзера, получишь дополнительные имя фамилия поля в таблице, здесь нужно тоже от Base наследоваться.

2022-01-19 07:38 UTC, matacoder commented on homework12/create_records.py
> +        Student(first_name="Roman", last_name="Petrov"),
База данных не нормализована в хранишь имена и фамилии в разных таблицах в двойном экземпляре.
А что, если студент еще и преподавателем является, например? Две одинаковые записи?

2022-01-19 13:30 UTC, coctel99 commented on homework12/models.py
> +class Student(User):
Но если я не буду наследоваться от Юзера, то мне придется каждый раз перед созданием Студента придется создавать нового Юзера и указывать Студенту user_id этого юзера. А при наследовании от Юзера он создается автоматически при создании Студента

2022-01-20 08:37 UTC, matacoder approved these changes
Ты готов к финалке, удачи тебе!

2022-01-20 08:37 UTC, matacoder commented on homework12/models.py
> +class Teacher(Base):
Отлично

2022-01-20 08:43 UTC, coctel99 commented on homework12/models.py
> +class Teacher(Base):
Спасибо!

2022-01-20 08:43 UTC, merged